### ISSUE TITLE
Decide on packaging strategy

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig-ui#19]
- Are we in `0.x.y` forever or do we [go to `1.0.0`](http://www.jongleberry.com/semver-has-failed-us.html)?
- Do we publish to NPM or just use Git tags for dependency management?

**Comment by jdesboeufs** [comment]
1.0.0 asap + NPM
We should review the `public API` before that.

**Comment by MattiSG** [comment]
UI is good to go IMO. Let's finish pending PRs and possibly #3 and publish! :shipit:

**Comment by MattiSG** [comment]
Re: discussion yesterday, let's have a small try at milestones!

I'd say #2, #3, #6 #17 and #18 are in for `1.0.0`.

**Comment by jdesboeufs** [comment]
I mean the JS API :)

**Comment by MattiSG** [comment]
The main export you mean? Working on it in #6  ^^

**Comment by MattiSG** [comment]
Do we agree on the [v1.0.0 milestone contents](https://github.com/sgmap/ludwig-ui/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0.0)? If yes, then let's close this issue.

**Comment by jdesboeufs** [comment]
Yes!
