### ISSUE TITLE
Lancer un test après modification

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig-ui#27]
En tant que contributeur d'un test,
Je peux voir les résultats d'un test dès sa création ou modification,
Pour ne pas croire par erreur qu'il est valide

Origine du besoin : expérience personnelle de contribution

**Comment by nanocom** [comment]
aussi : lancer un test juste à sa création (sinon on est obligé de lancer le test manuellement pour voir sa couleur)
