### ISSUE TITLE
Remove Ruby dependency

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig-ui#3]
Replace `compass` by a JS-based compiler for SASS assets.

Or, depending on the amount of styles, remove preprocessing altogether?

**Comment by jdesboeufs** [comment]
You should use [node-sass](https://github.com/sass/node-sass) through [grunt-sass](https://github.com/sindresorhus/grunt-sass).

Very easy to fix.

**Comment by MattiSG** [comment]
> This task uses libsass which is a Sass compiler in C++. In contrast to the original Ruby compiler, this one is much faster, but is missing some features, though improving quickly. It also doesn't support Compass.

@Flightan Since we install `compass` but have a very small amount of stylesheets, do you know if we need Compass?

**Comment by MattiSG** [comment]
> Very easy to fix.

Well, translating these 20 lines of options with no prior knowledge of Grunt nor `node-sass` is nontrivial  ;)
@jdesboeufs Could you handle this?

**Comment by MattiSG** [comment]
poke @Flightan

**Comment by MattiSG** [comment]
Ok, so we've made the switch to `grunt-sass` with @Flightan this in d7e2050… But new issues are coming up  ^^

- Compiling in `postinstall` depends on `devDependencies` (Obviously… We should have caught this in #18.)
- The temporary ugly fix I had in adding `npm install` before building in `postinstall` fails badly: it creates an infinite loop because of imagemin/imagemin#68.

So, it looks like we'll have to package compiled dependencies ourselves in a `prepublish`, which is not necessarily a bad thing.
However, the question is: if we don't delegate to users the responsibilty to compile, we can take it on ourselves to install gems properly. Since moving to `grunt-sass` makes us lose Compass features, do we still want to do the replacement?
