### ISSUE TITLE
Fixer le redirect sur la page de login

### ISSUE THREAD

**Issue by nanocom** [sgmap/ludwig-ui#31]
J'avais fait en sorte que lorsqu'on arrive sur ludwig on est redirigé sur la page de login si on est pas connecté, la page de login redirigeant vers la page demandée si la connexion est réussi (query param : targetUrl). Ce comportement ne fonctionne plus, serait bien de le réactiver.

**Comment by MattiSG** [comment]
Duplicate of #48.
