### ISSUE TITLE
Ajouter un template de description

### ISSUE THREAD

**Issue by MattiSG** [sgmap/ludwig-ui#35]
En tant que responsable de recette,
Je peux compléter une description préremplie plutôt qu’avoir un champ libre,
Pour mieux qualifier mes retours

**Comment by HelaG** [comment]
On a envoyé le mail aux "recetteurs". On peut considérer que la comm is done ?

**Comment by MattiSG** [comment]
@HelaG Si tu as vérifié que ça marchait et que tu es ok avec le contenu du texte, oui  :)

**Comment by HelaG** [comment]
C'est parfait pour moi! J'ai même créé un faux test pour garder le tag "Recette", histoire que les premiers recetteurs ait tout ce qu'il faut sous la main!
